name: bikewaysim
channels:
  - conda-forge
dependencies:
  - osmnx
  - pandas
  - geopandas
  - numpy
  - matplotlib
  - pyprojroot
  - scikit-learn
  - scipy
  - tqdm
  - beautifulsoup4 # for getting the timestamp of the geofabrik extract
  - branca # for legends
  - contextily
  - ipykernel # needed for running jupyter notebooks
  - osmium-tool # needed for processing osm extracts
  - laspy # needed for point cloud processing
  - lazrs-python # needed for point cloud processing
  - pip
  - pip:
      - rustworkx
      - similaritymeasures
      - stochopy
      - leuvenmapmatching