name: bikewaysim
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - affine=2.4.0=pyhd8ed1ab_0
  - asttokens=2.4.1=pyhd8ed1ab_0
  - attrs=24.2.0=pyh71513ae_0
  - aws-c-auth=0.7.31=hce3b56f_0
  - aws-c-cal=0.7.4=hf1fc857_1
  - aws-c-common=0.9.28=h2466b09_0
  - aws-c-compression=0.2.19=hf1fc857_1
  - aws-c-event-stream=0.4.3=hd0ca3c1_2
  - aws-c-http=0.8.10=heca9ddf_0
  - aws-c-io=0.14.18=h3831a8d_10
  - aws-c-mqtt=0.10.6=hf27581b_0
  - aws-c-s3=0.6.6=h56e9fbd_0
  - aws-c-sdkutils=0.1.19=hf1fc857_3
  - aws-checksums=0.1.20=hf1fc857_0
  - aws-crt-cpp=0.28.3=hd65be8e_5
  - aws-sdk-cpp=1.11.407=h25dd3c2_0
  - azure-core-cpp=1.13.0=haf5610f_0
  - azure-identity-cpp=1.9.0=h148e6f0_0
  - azure-storage-blobs-cpp=12.13.0=ha77ad07_0
  - azure-storage-common-cpp=12.8.0=h148e6f0_0
  - beautifulsoup4=4.12.3=py312haa95532_0
  - blosc=1.21.6=h85f69ea_0
  - branca=0.7.2=pyhd8ed1ab_0
  - brotli=1.1.0=h2466b09_2
  - brotli-bin=1.1.0=h2466b09_2
  - brotli-python=1.1.0=py312h275cf98_2
  - bzip2=1.0.8=h2466b09_7
  - c-ares=1.33.1=h2466b09_0
  - ca-certificates=2024.8.30=h56e8100_0
  - cairo=1.18.0=h32b962e_3
  - certifi=2024.8.30=pyhd8ed1ab_0
  - cffi=1.17.1=py312h4389bb4_0
  - cfitsio=4.4.1=hc2ea260_0
  - charset-normalizer=3.3.2=pyhd8ed1ab_0
  - click=8.1.7=win_pyh7428d3b_0
  - click-plugins=1.1.1=py_0
  - cligj=0.7.2=pyhd8ed1ab_1
  - colorama=0.4.6=pyhd8ed1ab_0
  - comm=0.2.2=pyhd8ed1ab_0
  - contextily=1.6.2=pyhd8ed1ab_0
  - contourpy=1.3.0=py312hd5eb7cc_2
  - cpython=3.12.6=py312hd8ed1ab_2
  - cycler=0.12.1=pyhd8ed1ab_0
  - debugpy=1.8.6=py312h275cf98_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - exceptiongroup=1.2.2=pyhd8ed1ab_0
  - executing=2.1.0=pyhd8ed1ab_0
  - expat=2.6.3=he0c23c2_0
  - fiona=1.10.1=py312hd215820_1
  - fmt=11.0.2=h7f575de_0
  - folium=0.17.0=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.14.2=hbde0cde_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.54.1=py312h4389bb4_0
  - freetype=2.12.1=hdaf720e_2
  - freexl=2.0.0=h8276f4a_0
  - gdal=3.9.2=py312h16ac12d_5
  - geographiclib=2.0=pyhd8ed1ab_0
  - geopandas=0.14.4=pyhd8ed1ab_0
  - geopandas-base=0.14.4=pyha770c72_0
  - geopy=2.4.1=pyhd8ed1ab_1
  - geos=3.13.0=h5a68840_0
  - geotiff=1.7.3=h496ac4d_3
  - h2=4.1.0=pyhd8ed1ab_0
  - hdf4=4.2.15=h5557f11_7
  - hdf5=1.14.3=nompi_h2b43c12_105
  - hpack=4.0.0=pyh9f0ad1d_0
  - hyperframe=6.0.1=pyhd8ed1ab_0
  - icu=75.1=he0c23c2_0
  - idna=3.10=pyhd8ed1ab_0
  - importlib-metadata=8.5.0=pyha770c72_0
  - importlib_resources=6.4.5=pyhd8ed1ab_0
  - intel-openmp=2024.2.1=h57928b3_1083
  - ipykernel=6.29.5=pyh4bbf305_0
  - ipython=8.27.0=pyh7428d3b_0
  - jedi=0.19.1=pyhd8ed1ab_0
  - jinja2=3.1.4=pyhd8ed1ab_0
  - joblib=1.4.2=pyhd8ed1ab_0
  - jsonschema=4.23.0=pyhd8ed1ab_0
  - jsonschema-specifications=2023.12.1=pyhd8ed1ab_0
  - jupyter_client=8.6.3=pyhd8ed1ab_0
  - jupyter_core=5.7.2=pyh5737063_1
  - kealib=1.5.3=h6c43f9b_2
  - kiwisolver=1.4.7=py312hd5eb7cc_0
  - krb5=1.21.3=hdf4eb48_0
  - lcms2=2.16=h67d730c_0
  - lerc=4.0.0=h63175ca_0
  - libabseil=20240722.0=cxx17_he0c23c2_1
  - libaec=1.1.3=h63175ca_0
  - libarchive=3.7.4=haf234dc_0
  - libblas=3.9.0=24_win64_mkl
  - libboost=1.84.0=h444863b_6
  - libbrotlicommon=1.1.0=h2466b09_2
  - libbrotlidec=1.1.0=h2466b09_2
  - libbrotlienc=1.1.0=h2466b09_2
  - libcblas=3.9.0=24_win64_mkl
  - libcrc32c=1.1.2=h0e60522_0
  - libcurl=8.10.1=h1ee3ff0_0
  - libdeflate=1.21=h2466b09_0
  - libexpat=2.6.3=he0c23c2_0
  - libffi=3.4.2=h8ffe710_5
  - libgdal=3.9.2=h57928b3_5
  - libgdal-core=3.9.2=hf78aeaf_5
  - libgdal-fits=3.9.2=h0a0b71e_5
  - libgdal-grib=3.9.2=hd2a089b_5
  - libgdal-hdf4=3.9.2=h430f241_5
  - libgdal-hdf5=3.9.2=had131a1_5
  - libgdal-jp2openjpeg=3.9.2=hed4c6cb_5
  - libgdal-kea=3.9.2=h95b1a77_5
  - libgdal-netcdf=3.9.2=h55e78d3_5
  - libgdal-pdf=3.9.2=ha1c78db_5
  - libgdal-pg=3.9.2=ha693a0f_5
  - libgdal-postgisraster=3.9.2=ha693a0f_5
  - libgdal-tiledb=3.9.2=hb8b5d01_5
  - libgdal-xls=3.9.2=hd0e23a6_5
  - libglib=2.82.1=h7025463_0
  - libgoogle-cloud=2.29.0=ha00044d_1
  - libgoogle-cloud-storage=2.29.0=he5eb982_1
  - libgrpc=1.65.5=ha20e22e_0
  - libhwloc=2.11.1=default_h8125262_1000
  - libiconv=1.17=hcfcfb64_2
  - libintl=0.22.5=h5728263_3
  - libjpeg-turbo=3.0.0=hcfcfb64_1
  - libkml=1.3.0=h538826c_1021
  - liblapack=3.9.0=24_win64_mkl
  - libnetcdf=4.9.2=nompi_h92078aa_114
  - libpng=1.6.44=h3ca93ac_0
  - libpq=16.4=hab9416b_2
  - libprotobuf=5.27.5=hcaed137_2
  - libre2-11=2023.09.01=h4eb7d71_3
  - librttopo=1.1.0=hd4c2148_17
  - libsodium=1.0.20=hc70643c_0
  - libspatialindex=2.0.0=h5a68840_0
  - libspatialite=5.1.0=h939089a_11
  - libsqlite=3.46.1=h2466b09_0
  - libssh2=1.11.0=h7dfc565_0
  - libtiff=4.7.0=hb151862_0
  - libwebp-base=1.4.0=hcfcfb64_0
  - libxcb=1.16=h013a479_1
  - libxml2=2.12.7=h0f24e4e_4
  - libzip=1.11.1=h25f2845_0
  - libzlib=1.3.1=h2466b09_1
  - lz4-c=1.9.4=hcfcfb64_0
  - lzo=2.10=hcfcfb64_1001
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - mapclassify=2.8.1=pyhd8ed1ab_0
  - markupsafe=2.1.5=py312h4389bb4_1
  - matplotlib-base=3.8.4=py312hfee7060_2
  - matplotlib-inline=0.1.7=pyhd8ed1ab_0
  - mercantile=1.2.1=pyhd8ed1ab_0
  - minizip=4.0.6=hb638d1e_0
  - mkl=2024.1.0=h66d3029_694
  - msys2-conda-epoch=20160418=1
  - munkres=1.1.4=pyh9f0ad1d_0
  - nbformat=5.10.4=pyhd8ed1ab_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_0
  - networkx=3.3=pyhd8ed1ab_1
  - numpy=1.26.4=py312h8753938_0
  - openjpeg=2.5.2=h3d672ee_0
  - openssl=3.3.2=h2466b09_0
  - osmium-tool=1.16.0=h015118d_3
  - osmnx=1.9.4=pyhd8ed1ab_0
  - packaging=24.1=pyhd8ed1ab_0
  - pandas=2.2.3=py312h72972c8_1
  - parso=0.8.4=pyhd8ed1ab_0
  - pcre2=10.44=h3d7b363_2
  - pickleshare=0.7.5=py_1003
  - pillow=10.4.0=py312h381445a_1
  - pip=24.2=pyh8b19718_1
  - pixman=0.43.4=h63175ca_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_1
  - platformdirs=4.3.6=pyhd8ed1ab_0
  - poppler=24.08.0=h9415970_1
  - poppler-data=0.4.12=hd8ed1ab_0
  - postgresql=16.4=hd835ec0_2
  - proj=9.5.0=hd9569ee_0
  - prompt-toolkit=3.0.48=pyha770c72_0
  - psutil=6.0.0=py312h4389bb4_1
  - pthread-stubs=0.4=hcd874cb_1001
  - pthreads-win32=2.9.1=hfa6e2cd_3
  - pure_eval=0.2.3=pyhd8ed1ab_0
  - pycparser=2.22=pyhd8ed1ab_0
  - pygments=2.18.0=pyhd8ed1ab_0
  - pyparsing=3.1.4=pyhd8ed1ab_0
  - pyproj=3.7.0=py312ha24589b_0
  - pyprojroot=0.3.0=pyhd8ed1ab_0
  - pysocks=1.7.1=pyh0701188_6
  - python=3.12.6=hce54a09_2_cpython
  - python-dateutil=2.9.0=pyhd8ed1ab_0
  - python-fastjsonschema=2.20.0=pyhd8ed1ab_0
  - python-tzdata=2024.2=pyhd8ed1ab_0
  - python_abi=3.12=5_cp312
  - pytz=2024.1=pyhd8ed1ab_0
  - pywin32=306=py312h53d5487_2
  - pyzmq=26.2.0=py312hd7027bb_2
  - rasterio=1.3.11=py312h363bed3_2
  - re2=2023.09.01=hd3b24a8_3
  - referencing=0.35.1=pyhd8ed1ab_0
  - requests=2.32.3=pyhd8ed1ab_0
  - rpds-py=0.20.0=py312h2615798_1
  - rtree=1.3.0=py312h9e53377_2
  - scikit-learn=1.5.2=py312h816cc57_1
  - scipy=1.13.1=py312h1f4e10d_0
  - setuptools=75.1.0=pyhd8ed1ab_0
  - shapely=2.0.6=py312h0c580ee_2
  - six=1.16.0=pyh6c4a22f_0
  - snappy=1.2.1=h23299a8_0
  - snuggs=1.4.7=pyhd8ed1ab_1
  - soupsieve=2.5=pyhd8ed1ab_1
  - spdlog=1.14.1=h9f2357e_1
  - sqlite=3.46.1=h2466b09_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - tbb=2021.13.0=hc790b64_0
  - threadpoolctl=3.5.0=pyhc1e730c_0
  - tiledb=2.26.2=h34a6a78_0
  - tk=8.6.13=h5226925_1
  - tornado=6.4.1=py312h4389bb4_1
  - tqdm=4.66.5=pyhd8ed1ab_0
  - traitlets=5.14.3=pyhd8ed1ab_0
  - typing_extensions=4.12.2=pyha770c72_0
  - tzdata=2024a=h8827d51_1
  - ucrt=10.0.22621.0=h57928b3_0
  - uriparser=0.9.8=h5a68840_0
  - urllib3=2.2.3=pyhd8ed1ab_0
  - vc=14.3=h8a93ad2_21
  - vc14_runtime=14.40.33810=ha82c5b3_21
  - vs2015_runtime=14.40.33810=h3bf8584_21
  - wcwidth=0.2.13=pyhd8ed1ab_0
  - wheel=0.44.0=pyhd8ed1ab_0
  - win_inet_pton=1.1.0=pyh7428d3b_7
  - xerces-c=3.2.5=he0c23c2_2
  - xorg-libxau=1.0.11=hcd874cb_0
  - xorg-libxdmcp=1.1.3=hcd874cb_0
  - xyzservices=2024.9.0=pyhd8ed1ab_0
  - xz=5.2.6=h8d14728_0
  - zeromq=4.3.5=he1f189c_5
  - zipp=3.20.2=pyhd8ed1ab_0
  - zlib=1.3.1=h2466b09_1
  - zstandard=0.23.0=py312h7606c53_1
  - zstd=1.5.6=h0ea2cb4_0
  - pip:
      - rustworkx==0.15.1
      - similaritymeasures==1.1.0
      - stochopy==2.3.0
prefix: C:\Users\tpassmore6\Anaconda3\envs\bikewaysim
