name: bikewaysim
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - beautifulsoup4
  - branca
  - contextily
  - folium
  - geopandas
  - ipykernel
  #- osmium-tool
  - osmnx
  - pip
  - python
  - scikit-learn
  - scipy
  - tqdm
  - pip:
      - rustworkx
      - similaritymeasures
      - stochopy